"""Phase-2 v1 defaults (single source of truth)."""

from __future__ import annotations

V1_DEFAULTS_VERSION = "v1-defaults-2026-05-07"

ENERGY_MIN = 0.0
ENERGY_MAX = 1.0
ENERGY_EPSILON = 1e-3

DEFAULT_CREATURE_ENERGY = 0.80
DEFAULT_PRODUCER_ENERGY = 0.65
DEFAULT_METABOLISM_DRAIN_PER_TICK = 0.0005

DEATH_ENERGY_THRESHOLD = 0.02
CORPSE_DEPOSIT_AMOUNT = 0.30
SPORE_ON_DEATH_AMOUNT = 0.08

FOOD_CONSUMER_GAIN = 0.20
FOOD_PREY_COST = 0.22

PHOTOSYNTHESIS_RATE = 0.010
SWEET_EMIT_RATE = 0.005
MANA_GEO_ABSORB_RATE = 0.003

# Epigenome / stress markers (creatures-spec-v1 §4)
CLUSTER_STRESS_THRESHOLD = 0.70
STRESS_MARKER_DECAY_PER_SEC = 0.02
EPIGENOME_TAU_SEC = 60.0
EPIGENOME_MULT_MIN = 0.85
EPIGENOME_MULT_MAX = 1.15
EPIGENOME_DELTA_CLAMP = 0.15
PIGMENTATION_DELTA_CLAMP = 0.15

FAMINE_ENERGY_THRESHOLD = 0.35
ABUNDANCE_ENERGY_THRESHOLD = 0.85
PREDATION_ALARM_THRESHOLD = 0.25

# Reproduction (creatures-spec-v1 tick step 10)
REPRODUCTION_ENERGY_THRESHOLD = 0.85
REPRODUCTION_STRESS_THRESHOLD = 0.35
REPRODUCTION_PARENT_ENERGY_COST = 0.35
REPRODUCTION_OFFSPRING_ENERGY = 0.50
MAX_POPULATION_PER_SPECIES = 32
GENOME_DRIFT_SCALE = 0.02
EPIGENOME_INHERIT_BLEND = 0.85
EPIGENOME_DRIFT_SCALE = 0.01
MARKER_SMOOTHING = 0.12

STRESS_GAIN_FAMINE = 0.025
STRESS_GAIN_PREDATION = 0.035
STRESS_RELIEF_ABUNDANCE = 0.015
STRESS_RELIEF_FED = 0.02

# Population / adaptation cache (creatures-spec-v1 §6)
CLUSTER_MIN_SIZE = 3
POPULATION_SCAN_INTERVAL = 30
FALLBACK_SUBTREE_KEY = "dormancy"
CACHE_PROMOTE_MIN_SAMPLES = 5
CACHE_PROMOTE_MIN_SUCCESS_RATE = 0.60
CACHE_PROMOTE_MIN_STRESS_REDUCTION = 0.05
CACHE_DEMOTE_SUCCESS_RATE = 0.35
CACHE_INVALIDATE_FAILURES = 3

# LLM slow path (creatures-spec-v1 §5)
LLM_REQUEST_TIMEOUT_SEC = 5.0
LLM_AUTHOR_REQUEST_TIMEOUT_SEC = 90.0
LLM_RETRY_MAX_ATTEMPTS = 2
LLM_AUTHOR_RETRY_MAX_ATTEMPTS = 4
LLM_CIRCUIT_FAILURE_THRESHOLD = 3
LLM_CIRCUIT_COOLDOWN_SEC = 60
